[package]
name = "rust小白实战案例库"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["multipart"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros", "net"] }
bytes = "1.5"
tower-http = { version = "0.6.2", features = ["fs"] }
