[package]
name = "axum_chat_v8"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.8", features = ["ws"] }
# 高并发下的线程安全哈希表
dashmap = "6.1.0"
# 用于 WebSocket 的 Sink/Stream 处理
futures-util = "0.3.31"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
